version: '3.6'

networks:
  testing-net:

volumes:
  database-go: {}

services:
  postgresql:
    image: postgres:latest
    restart: always
    networks:
      - 'testing-net'
    volumes: 
      - database-go:/var/lib/postgresql/data
    environment :
      POSTGRES_PASSWORD: 0000

  app:
    build: .
    networks:
      - 'testing-net'
    ports:
      - '8000:8000'
    environment:
      IP: 0.0.0.0
      POSTGRES_URL: postgresql
      PORT: 8000
      POSTGRES_PASSWORD: 0000
    depends_on: 
      - 'postgresql'
